FROM golang:1.7-alpine

COPY . /go/src/github.com/onedata/docker-volume-onedata
WORKDIR /go/src/github.com/onedata/docker-volume-onedata

RUN set -ex \
    && apk add --no-cache --virtual .build-deps \
    gcc libc-dev \
    && go install --ldflags '-extldflags "-static"' \
    && apk del .build-deps

CMD ["/go/bin/docker-volume-onedata"]
